kind = "DojoModel"
class_hash = "0x5c1c32a3c95e33ee9f5c3313ee5f90d0da174c9ab8198e9aa640cdfe1009118"
original_class_hash = "0x5c1c32a3c95e33ee9f5c3313ee5f90d0da174c9ab8198e9aa640cdfe1009118"
abi = "manifests/dev/abis/base/models/paved_models_game_game.json"
name = "paved::models::game::game"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "over"
type = "bool"
key = false

[[members]]
name = "players"
type = "u128"
key = false

[[members]]
name = "player_count"
type = "u32"
key = false

[[members]]
name = "tiles"
type = "u128"
key = false

[[members]]
name = "tile_count"
type = "u32"
key = false

[[members]]
name = "start_time"
type = "u64"
key = false

[[members]]
name = "duration"
type = "u64"
key = false

[[members]]
name = "prize"
type = "felt252"
key = false

[[members]]
name = "score"
type = "u32"
key = false

[[members]]
name = "mode"
type = "u8"
key = false

[[members]]
name = "deck"
type = "u8"
key = false

[[members]]
name = "seed"
type = "felt252"
key = false
