kind = "DojoModel"
class_hash = "0x3fb8b10eda1689b529d3237d481b4d7a9f018e0f07a2c9317e5b04429b36ef8"
original_class_hash = "0x3fb8b10eda1689b529d3237d481b4d7a9f018e0f07a2c9317e5b04429b36ef8"
abi = "manifests/dev/abis/base/models/paved_models_game_game.json"
name = "paved::models::game::game"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "over"
type = "bool"
key = false

[[members]]
name = "tiles"
type = "u128"
key = false

[[members]]
name = "tile_count"
type = "u32"
key = false

[[members]]
name = "start_time"
type = "u64"
key = false

[[members]]
name = "score"
type = "u32"
key = false

[[members]]
name = "seed"
type = "felt252"
key = false

[[members]]
name = "mode"
type = "u8"
key = false
