kind = "DojoModel"
class_hash = "0x57c41990f302d13d534792f39239a5e325d2ead36e93823f1086ff242f3dc19"
original_class_hash = "0x57c41990f302d13d534792f39239a5e325d2ead36e93823f1086ff242f3dc19"
abi = "manifests/dev/abis/base/models/paved_models_character_character_position.json"
name = "paved::models::character::character_position"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "tile_id"
type = "u32"
key = true

[[members]]
name = "spot"
type = "u8"
key = true

[[members]]
name = "player_id"
type = "felt252"
key = false

[[members]]
name = "index"
type = "u8"
key = false
