[package]
cairo-version = "2.4.0"
name = "paved"
version = "0.0.0"
edition = "2023_10"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate plan && sozo migrate apply && ./scripts/katana.sh"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.6.0" }
origami = { git = "https://github.com/dojoengine/origami", tag = "v0.6.0" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.world]
name = "Paved"
description = "A strategic onchain tile laying game."
cover_uri = "https://paved.gg/assets/placeholder.png"
icon_uri = "https://paved.gg/assets/logo.png"
website = "https://paved.gg"

[tool.dojo.world.socials]
x = "https://x.com/pavedgame"
discord = "https://discord.com/invite/realmsworld"
github = "https://github.com/stolslilabs/paved"

[tool.dojo.env]
# Katana
rpc_url = "http://localhost:5050/"
account_address = "0x6162896d1d7ab204c7ccac6dd5f8e9e7c25ecd5ae4fcb4ad32e57786bb46e03"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"

# Dev
# rpc_url = "https://api.cartridge.gg/x/paved-dev/katana/"
# account_address = "0x52c755d7cf7375c10af11f22d899b46a1dc222fa0a30c78e5805584c0ed69d5"
# private_key = "0x273039126a440372bb32361f17cbc98df3426480c50916ad68e28a82746d213"

# Realms
# rpc_url = "https://api.cartridge.gg/x/realms/katana/"
# account_address = "0x379900b695d11ec52b13557de5ebd864eb2f36f14ff56560b028992585b7515"
# private_key = "0x62bb13afe7963fd97e568db915e331956ddc4ba13dda9b787a6648a5b840626"

# Sepolia
# rpc_url = "https://rpc.nethermind.io/sepolia-juno/?apikey=IklrGtteSW0anXtAfnkQGBJuYpSmbLi0YJ5afM2aJsW8JsH1"
# account_address = "0x059b1a0c489b635d7c7f43594d187362ddd2dcea6c82db4eef2579fd185b3753"
# private_key = "0xaf7f0b88b7ee7faf8065517cd565d9f9dcd013dd2382a0f1e6b3559f0fe57a"
