kind = "DojoContract"
class_hash = "0x287cc5270b1093fd065cb8cfb9dbd446bd0a589c2e60daa7c94dca89f546951"
original_class_hash = "0x287cc5270b1093fd065cb8cfb9dbd446bd0a589c2e60daa7c94dca89f546951"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/paved_systems_daily_daily.json"
reads = []
writes = []
computed = []
name = "paved::systems::daily::daily"
