kind = "DojoContract"
class_hash = "0x65babe13bd150623e83a655b9905abb1bacaca655322929fb0cff8f091249e1"
original_class_hash = "0x65babe13bd150623e83a655b9905abb1bacaca655322929fb0cff8f091249e1"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/paved_systems_daily_daily.json"
reads = []
writes = []
computed = []
name = "paved::systems::daily::daily"
