kind = "DojoContract"
class_hash = "0x10b1524836d23753bbd2d3ffd4c4efd9e751aff92ac0fe559eb5916585b4b1c"
original_class_hash = "0x10b1524836d23753bbd2d3ffd4c4efd9e751aff92ac0fe559eb5916585b4b1c"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/paved_systems_play_play.json"
reads = []
writes = []
computed = []
name = "paved::systems::play::play"
