kind = "DojoContract"
class_hash = "0x76692990a3cb3af083626cd80a3d7e0cb394e4b0ff935c7215c9541793ea4b1"
original_class_hash = "0x76692990a3cb3af083626cd80a3d7e0cb394e4b0ff935c7215c9541793ea4b1"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/paved_systems_host_host.json"
reads = []
writes = []
computed = []
name = "paved::systems::host::host"
