kind = "DojoContract"
class_hash = "0x1ee22fe2bdbf6b920a95128251059775ff2464719a4e622be26281ecd10b4d4"
original_class_hash = "0x1ee22fe2bdbf6b920a95128251059775ff2464719a4e622be26281ecd10b4d4"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/paved_systems_host_host.json"
reads = []
writes = []
computed = []
name = "paved::systems::host::host"
