kind = "DojoContract"
class_hash = "0x11e8071e2e5f2eba42e164394b50738706a0c190d8cb696fddb3cf8e521e82d"
original_class_hash = "0x11e8071e2e5f2eba42e164394b50738706a0c190d8cb696fddb3cf8e521e82d"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/paved_systems_play_play.json"
reads = []
writes = []
computed = []
name = "paved::systems::play::play"
