kind = "DojoContract"
class_hash = "0x20c111ef0073fc376498445dc305ba71f25c694195fb4a874d8638e908fea1"
original_class_hash = "0x20c111ef0073fc376498445dc305ba71f25c694195fb4a874d8638e908fea1"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/paved_systems_weekly_weekly.json"
reads = []
writes = []
computed = []
name = "paved::systems::weekly::weekly"
