kind = "DojoContract"
class_hash = "0x38c0b42510292e7a385221df0daf12928ca3ac6969da1912cc7803b44f63a7a"
original_class_hash = "0x38c0b42510292e7a385221df0daf12928ca3ac6969da1912cc7803b44f63a7a"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/paved_systems_weekly_weekly.json"
reads = []
writes = []
computed = []
name = "paved::systems::weekly::weekly"
